# Generated by Django 2.1.5 on 2019-01-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('question_text', models.CharField(max_length=200)),
                ('software', models.CharField(max_length=400)),
                ('os_supported', models.CharField(max_length=400)),
                ('languages', models.CharField(max_length=400)),
                ('currencies', models.CharField(max_length=400)),
                ('deposit_methods', models.CharField(max_length=400)),
                ('minimal_deposit', models.CharField(max_length=400)),
                ('withdrawal_methods', models.CharField(max_length=400)),
                ('withdrawal_limits', models.CharField(max_length=400)),
                ('withdrawal_min_amount', models.CharField(max_length=400)),
                ('established_on', models.CharField(max_length=400)),
                ('jurisdiction', models.CharField(max_length=400)),
                ('sister_casinos', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casinos.Casino'),
        ),
    ]
