# Generated by Django 2.1.5 on 2019-01-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='question_text',
        ),
        migrations.AddField(
            model_name='casino',
            name='casino_description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='casino',
            name='casino_name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
