# Generated by Django 2.1.5 on 2019-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_auto_20190111_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='casino_link',
            field=models.CharField(default='SOMESTRING', max_length=200),
        ),
        migrations.AddField(
            model_name='casino',
            name='rating_ours',
            field=models.CharField(default='SOMESTRING', max_length=5),
        ),
        migrations.AddField(
            model_name='casino',
            name='rating_users',
            field=models.CharField(default='SOMESTRING', max_length=5),
        ),
        migrations.AlterField(
            model_name='casino',
            name='casino_description',
            field=models.CharField(default='SOMESTRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='casino',
            name='casino_name',
            field=models.CharField(default='SOMESTRING', max_length=200),
        ),
    ]
