# Generated by Django 2.1.5 on 2019-01-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0003_auto_20190111_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='casino_icon',
            field=models.ImageField(default='resources/index.jfif', upload_to=None),
        ),
    ]
