# Generated by Django 2.1.5 on 2019-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_auto_20190111_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='choice_text',
            new_name='bonus_name',
        ),
        migrations.RenameField(
            model_name='bonus',
            old_name='question',
            new_name='casino',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='votes',
        ),
        migrations.AddField(
            model_name='bonus',
            name='additional_information',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_amount',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_code',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_description',
            field=models.CharField(default='qwe', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='games',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='max_deposit',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='min_deposit',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='valid_for',
            field=models.CharField(default='qwe', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casino',
            name='casino_icon',
            field=models.ImageField(default='resources\\index.jfif', upload_to=None),
        ),
    ]
