# Generated by Django 2.1.5 on 2019-01-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0010_auto_20190113_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='date_added',
            field=models.DateTimeField(default='1111-11-11 11:11', verbose_name='date added'),
            preserve_default=False,
        ),
    ]
