from django.db import models


class Casino(models.Model):
    date_added = models.DateTimeField('date added')
    casino_icon = models.ImageField(upload_to='documents/%Y/%m/%d', height_field=None, width_field=None,default='resources\index.jfif')
    casino_name = models.CharField(max_length=200)
    casino_description = models.CharField(max_length=2000)
    software = models.CharField(max_length=400)
    os_supported = models.CharField(max_length=400)
    languages = models.CharField(max_length=400)
    currencies = models.CharField(max_length=400)
    deposit_methods = models.CharField(max_length=400)
    minimal_deposit = models.CharField(max_length=400)
    withdrawal_methods = models.CharField(max_length=400)
    withdrawal_limits = models.CharField(max_length=400)
    withdrawal_min_amount = models.CharField(max_length=400)
    established_on = models.CharField(max_length=400)
    withdrawal_min_amount = models.CharField(max_length=400)
    established_on = models.CharField(max_length=400)
    jurisdiction= models.CharField(max_length=400)
    sister_casinos = models.CharField(max_length=400)
    casino_link = models.CharField(max_length=200)
    rating_ours = models.CharField(max_length=5)
    rating_users = models.CharField(max_length=5)
class Bonus(models.Model):
    date_added = models.DateTimeField('date added')
    casino = models.ForeignKey(Casino, on_delete=models.CASCADE)
    bonus_name   = models.CharField(max_length=200)
    bonus_description = models.CharField(max_length=2000)
    bonus_amount     = models.CharField(max_length=400)
    bonus_code = models.CharField(max_length=400)
    valid_for = models.CharField(max_length=400)
    min_deposit = models.CharField(max_length=400)
    max_deposit = models.CharField(max_length=400)
    games = models.CharField(max_length=400)
    additional_information = models.CharField(max_length=400)